//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupSoftGraphics.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Users")]
        public string racineRecherche {
            get {
                return ((string)(this["racineRecherche"]));
            }
            set {
                this["racineRecherche"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoShutDown {
            get {
                return ((bool)(this["autoShutDown"]));
            }
            set {
                this["autoShutDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string heure {
            get {
                return ((string)(this["heure"]));
            }
            set {
                this["heure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string minute {
            get {
                return ((string)(this["minute"]));
            }
            set {
                this["minute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\dev\\testBackup")]
        public string path {
            get {
                return ((string)(this["path"]));
            }
            set {
                this["path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string period {
            get {
                return ((string)(this["period"]));
            }
            set {
                this["period"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>1</string>
  <string>2</string>
  <string>3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection nbSavesSource {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["nbSavesSource"]));
            }
            set {
                this["nbSavesSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system@automotor-france.com")]
        public string from {
            get {
                return ((string)(this["from"]));
            }
            set {
                this["from"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("92150sur")]
        public string MDPfrom {
            get {
                return ((string)(this["MDPfrom"]));
            }
            set {
                this["MDPfrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.auth.orange-business.com")]
        public string SMTP {
            get {
                return ((string)(this["SMTP"]));
            }
            set {
                this["SMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int port {
            get {
                return ((int)(this["port"]));
            }
            set {
                this["port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jcambray@automotor-france.com")]
        public string to {
            get {
                return ((string)(this["to"]));
            }
            set {
                this["to"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SSL {
            get {
                return ((bool)(this["SSL"]));
            }
            set {
                this["SSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string nbSaves {
            get {
                return ((string)(this["nbSaves"]));
            }
            set {
                this["nbSaves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1</string>
  <string>2</string>
  <string>3</string>
  <string>4</string>
  <string>5</string>
  <string>6</string>
  <string>7</string>
  <string>8</string>
  <string>9</string>
  <string>10</string>
  <string>11</string>
  <string>12</string>
  <string>13</string>
  <string>14</string>
  <string>15</string>
  <string>16</string>
  <string>17</string>
  <string>18</string>
  <string>19</string>
  <string>20</string>
  <string>21</string>
  <string>22</string>
  <string>23</string>
  <string>24</string>
  <string>25</string>
  <string>26</string>
  <string>27</string>
  <string>28</string>
  <string>29</string>
  <string>30</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection periodSource {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["periodSource"]));
            }
            set {
                this["periodSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>00</string>
  <string>01</string>
  <string>02</string>
  <string>03</string>
  <string>04</string>
  <string>05</string>
  <string>06</string>
  <string>07</string>
  <string>08</string>
  <string>09</string>
  <string>10</string>
  <string>11</string>
  <string>12</string>
  <string>13</string>
  <string>14</string>
  <string>15</string>
  <string>16</string>
  <string>17</string>
  <string>18</string>
  <string>19</string>
  <string>20</string>
  <string>21</string>
  <string>22</string>
  <string>23</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection heureSource {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["heureSource"]));
            }
            set {
                this["heureSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>00</string>\r\n  <string>01</string>\r\n  <string>02</string>\r\n  <string>03</s" +
            "tring>\r\n  <string>04</string>\r\n  <string>05</string>\r\n  <string>06</string>\r\n  <" +
            "string>07</string>\r\n  <string>08</string>\r\n  <string>09</string>\r\n  <string>10</" +
            "string>\r\n  <string>11</string>\r\n  <string>12</string>\r\n  <string>13</string>\r\n  " +
            "<string>14</string>\r\n  <string>15</string>\r\n  <string>16</string>\r\n  <string>17<" +
            "/string>\r\n  <string>18</string>\r\n  <string>19</string>\r\n  <string>20</string>\r\n " +
            " <string>21</string>\r\n  <string>22</string>\r\n  <string>23</string>\r\n  <string>24" +
            "</string>\r\n  <string>25</string>\r\n  <string>26</string>\r\n  <string>27</string>\r\n" +
            "  <string>28</string>\r\n  <string>29</string>\r\n  <string>30</string>\r\n  <string>3" +
            "1</string>\r\n  <string>32</string>\r\n  <string>33</string>\r\n  <string>34</string>\r" +
            "\n  <string>35</string>\r\n  <string>36</string>\r\n  <string>37</string>\r\n  <string>" +
            "38</string>\r\n  <string>39</string>\r\n  <string>40</string>\r\n  <string>41</string>" +
            "\r\n  <string>42</string>\r\n  <string>43</string>\r\n  <string>44</string>\r\n  <string" +
            ">45</string>\r\n  <string>46</string>\r\n  <string>47</string>\r\n  <string>48</string" +
            ">\r\n  <string>49</string>\r\n  <string>50</string>\r\n  <string>51</string>\r\n  <strin" +
            "g>52</string>\r\n  <string>53</string>\r\n  <string>54</string>\r\n  <string>55</strin" +
            "g>\r\n  <string>56</string>\r\n  <string>57</string>\r\n  <string>58</string>\r\n  <stri" +
            "ng>59</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection minuteSource {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["minuteSource"]));
            }
            set {
                this["minuteSource"] = value;
            }
        }
    }
}
